oferta_homepage:
    path:     /hello/{name}
    defaults: { _controller: OfertaBundle:Default:index }
    
pagina_ayuda:
    path:     /ayuda
    defaults: { _controller: OfertaBundle:Default:ayuda }
    
pagina_estatica:
    path:     /sitio/{pagina}
    defaults: { _controller: OfertaBundle:Sitio:estatica }

portada:
    path:     /{ciudad}
    defaults: { _controller: OfertaBundle:Default:portada, ciudad: null }

_portada:
    path:     /
    defaults: { _controller: OfertaBundle:Default:portada }

oferta:
    path:     /{ciudad}/ofertas/{slug}
    defaults: { _controller: OfertaBundle:Default:oferta }